# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: www.youcheyue.com
description: Youcheyue website
author:
  name: Youcheyue Team

url: http://www.youcheyue.com

source: app
destination: .tmp

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

permalink: /blog/:title.html

# Markdown library
markdown: redcarpet

highlighter: pygments

paginate: 8
paginate_path: /blog/page:num

gems:
- jekyll-redirect-from
